version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  sam: circleci/aws-sam-serverless@2.0.0

workflows:
  build_and_deploy:
    jobs:
      - sam/build:
          - checkout
          - sam/install
          - run sam build
      - sam/deploy:
          name: deploy-$ENVIRONMENT
          requires:
            - sam/build
          s3-bucket: mx-cloudformation-$ENVIRONMENT
          stack-name: lambda-template-$ENVIRONMENT
          template: ../template.yml
